### ISSUE TITLE
[Documentation] Fake Issue created.

### ISSUE THREAD

**Issue by rakshit234** [Nitesh-thapliyal/approach-2#2]
Ye issue raise krne ko bola gya hai mujhe.

**Comment by adityamangal1** [comment]
LGTM @Nitesh-thapliyal @rakshit234

**Comment by Nitesh-thapliyal** [comment]
> Ye issue raise krne ko bola gya hai mujhe.

Thanks for raising the issue

**Comment by adityamangal1** [comment]
<img align="right" alt="GIF" src="https://c.tenor.com/uKjKZFAvCoMAAAAC/laughing-laugh.gif" width="400" height="300" />

**Comment by rakshit234** [comment]
Contribute karskta?

**Comment by adityamangal1** [comment]
Please asssign this to me

**Comment by rakshit234** [comment]
![image](https://user-images.githubusercontent.com/52824782/132506554-f9ea416c-4902-46f7-82ab-9df0742bafa5.png)

**Comment by Piyush-Codes7** [comment]
I can work better than rakshit...assign this to me!

**Comment by adityamangal1** [comment]
Piyush is noob

**Comment by rakshit234** [comment]
No one asked you Piyush..

**Comment by adityamangal1** [comment]
I have linked my PR @Nitesh-thapliyal 😄

**Comment by Piyush-Codes7** [comment]
@rakshit234 @adityamangal1 you both noobs...let me work on this

**Comment by adityamangal1** [comment]
<img align="right" alt="GIF" src="https://miro.medium.com/max/650/1*ODQUZPiwWu04XxKX4f2jbg.jpeg" width="400" height="300" />

**Comment by adityamangal1** [comment]
#1
